name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release or a pre-release is published
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Publish
        if: ${{ !github.event.release.prerelease }}
        run: npm publish --provenance --access=public

      - name: Publish Pre-Release
        if: ${{ github.event.release.prerelease }}
        run: |
          # Strip leading "v" from tag. E.g. "v1.2.0-beta" -> "1.2.0-beta"
          CLEAN_TAG=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          jq ".version=\"${CLEAN_TAG}\"" package.json > package.json.deploy
          cp package.json.deploy package.json

          npm publish --provenance --tag next --access=public
